{% set name = "pugixml" %}
{% set version = "1.9" %}
{% set sha256 = "7ac060048bf00da4b3902cf411f0ba9f048cdc5580eed1f5a27ff51be4a38243" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeux/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake  # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libpugixml.a"  # [unix]
    - test -f "${PREFIX}/include/pugixml.hpp"  # [unix]
    - if not exist %LIBRARY_LIB%\\pugixml.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\pugiconfig.hpp exit 1  # [win]

about:
  home: http://pugixml.org/
  license: MIT
  license_family: MIT
  license_file: README.md
  summary: 'Light-weight, simple and fast XML parser for C++ with XPath support'
  description: |
    pugixml is a C++ XML processing library, which consists of a DOM-like interface
    with rich traversal/modification capabilities, an extremely fast XML parser which
    constructs the DOM tree from an XML file/buffer, and an XPath 1.0 implementation
    for complex data-driven tree queries. Full Unicode support is also available, with
    Unicode interface variants and conversions between different Unicode encodings
    (which happen automatically during parsing/saving)
  doc_url: http://pugixml.org/
  dev_url: https://github.com/zeux/pugixml

extra:
  recipe-maintainers:
    - scopatz
    - SylvainCorlay
