# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "E+1TI9ssXXBlUtb3ump2gx/8nxJDqZL8hLZsfaaxN3pNYK1T9NDTUnglMWzAcIUGshQN5IeajlVZTdU2PjbBbVf2S4vITB8j6xtZOe1wYpk1khh+dGzfIqJjEScF/7W0u1qTWoBcvOvPusXP9XZEfL3dkDJZWfo5LidC4qlaYHgnHvr34u7iZQKrlpDf3TvFuMQuzmm+qe8ZblvjNG6fC8ikSTB0fuSvJzB4Js8Y1mor6ttedOa016k3ubMjljMvGQJXDBeScYwW1okdBCPdoab+da0+pNpIKvMGlQpfaFyt1smogHgU87UZXfHBFt97XLye8P9aGePaGsEolwiiIdvS2nCvaaZ1pNz9fQl7o3XS3/0VUomesiFm1S7Gw6BWRxkhrCPo/LAtFS4qvl2YkJOm1xhcOHKjKs+xMd7nykzh7BnCdX+NChnN5C7UCv5gFL+2UGg31pno1Zg6nGRXTNUPYHj+hw+VNfg7q1rwZuwTsxMlU5BdgVJ9wcG3511FP16crVyn7ys7XVjBkslnIw0M4h/dfAoc6ntudNS2ISV2Trz+ncaICbjWgNHndlp3RMeSrP8ajd4HCyx9ct4aM1BvtCs1sbik4KodkX+dZGlcXvhIhNFaDMbhB2hNPf+2+NnfyauJUhbX+kYtYt0jfJU0gjJ9gAfOEu5CQE/DOv0="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi