# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "E+1TI9ssXXBlUtb3ump2gx/8nxJDqZL8hLZsfaaxN3pNYK1T9NDTUnglMWzAcIUGshQN5IeajlVZTdU2PjbBbVf2S4vITB8j6xtZOe1wYpk1khh+dGzfIqJjEScF/7W0u1qTWoBcvOvPusXP9XZEfL3dkDJZWfo5LidC4qlaYHgnHvr34u7iZQKrlpDf3TvFuMQuzmm+qe8ZblvjNG6fC8ikSTB0fuSvJzB4Js8Y1mor6ttedOa016k3ubMjljMvGQJXDBeScYwW1okdBCPdoab+da0+pNpIKvMGlQpfaFyt1smogHgU87UZXfHBFt97XLye8P9aGePaGsEolwiiIdvS2nCvaaZ1pNz9fQl7o3XS3/0VUomesiFm1S7Gw6BWRxkhrCPo/LAtFS4qvl2YkJOm1xhcOHKjKs+xMd7nykzh7BnCdX+NChnN5C7UCv5gFL+2UGg31pno1Zg6nGRXTNUPYHj+hw+VNfg7q1rwZuwTsxMlU5BdgVJ9wcG3511FP16crVyn7ys7XVjBkslnIw0M4h/dfAoc6ntudNS2ISV2Trz+ncaICbjWgNHndlp3RMeSrP8ajd4HCyx9ct4aM1BvtCs1sbik4KodkX+dZGlcXvhIhNFaDMbhB2hNPf+2+NnfyauJUhbX+kYtYt0jfJU0gjJ9gAfOEu5CQE/DOv0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
