travis:
  secure:
    BINSTAR_TOKEN: KF4XyhHUcX2vScVie8yzy9h4INmFg60Y29bqYYeNIdiAfIGPwCQSltJJfCJ4pbPeOUkapkOHm3n7zzApT9YMXqVJ01gh1wDW8HyI6FgD/9DxglRzfCx4unG6WdGdvMwSRMU33FoGIOT75SmAQ5e1kk0vvl4jlnQjzIkKrSMufGSEq2aCJguckZHh59FRpw9DlG4v8lcxAwGeL00gKdI/SpObV3cKsHP5978bQ+epIdcFzL/Ldlx3mhnBIVte9peucZUv8c/RJyKLYCZk5Ci/ujCxPEGPenNdWXAKY82XV4ziusMTsAdo+ilZ5lHG8nYReJQ1WxqaiXOoTGXmzFhtI5OZm71uFTfxadaLVHj6WLuMOgmYJFSBKm+IElJizJPZyJB7Rpf/c4afh72DDcrvwcrELFU8xQ+19GqjobEcGK4IwefKLNjF5xZiJYPAq/rG6KoAEmXYtmjo6TRkZvN169edmY5QIKq+pM5jGHsOzBtZX/2VfbjEz4tWcHkE3McZLo7Ww60ACeuply1pILbfzfbCAv4CQeAiRr9YUU1yufDAA5dH2OLmzDJCzZokeJzmLv8TlJf0tyVpKMzgCgP0YV06BI1Wlfdx43eSs2hatiFz29Uaw9WJhUg1MNTQnAK1sU/+EDwbHXr6a/N7Mr/5x5qiMmZdndNBKvQQ2uamuJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
